feat: new pipelines

diff --git a/.github/workflows/gradle-publish.yml b/.github/workflows/gradle-publish.yml
--- a/.github/workflows/gradle-publish.yml
+++ b/.github/workflows/gradle-publish.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: 'Versão para o release (ex: 1.2.3)'
+        description: 'Version to release (e.g., 1.0.0)'
         required: true
         type: string
 
@@ -23,6 +23,17 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
+
+      - name: Check if Release Exists
+        id: check_release
+        run: |
+          TAG_NAME="v${{ github.event.inputs.version }}"
+          if gh release view "$TAG_NAME" > /dev/null 2>&1; then
+            echo "Version $TAG_NAME already exists. Aborting release process."
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set up JDK 25
         uses: actions/setup-java@v4
